config/routes.rb
Rails.application.routes.draw do

  get 'trials/new'

  devise_for :users
  root to: 'examinations#index'
  get 'home/index'

  resources :examinations do
    resources :trials, only: [:new, :create]
  end
  resources :questions
  namespace :admin do
  resources :examinations
  end

end

app/models/examination.rb
class Examination < ActiveRecord::Base
  has_many :questions
  has_many :trials
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :examination
  validates :answer, numericality: { only_integer: true, greater_than: 0, less_than: 3 }

  def answer_text
    answer == 1 ? "×" : "○" #条件に合えば左が結果として出る(三項演算子)
    # if answer == 1
    #   "×"
    # else
    #   "○"
    # end
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :trial
  belongs_to :question
  delegate :user, to: :trial # userがきたらtrialに任せてしまう（委譲）
  delegate :text, to: :question

  validates :answer, numericality: { only_integer: true, greater_than: 0, less_than: 3 }

  def correct?
    answer == question.answer #自分の回答したものがあっているかどうか
  end
end

app/models/trial.rb
class Trial < ActiveRecord::Base
  belongs_to :user
  # belongs_to :examination
  has_many :results
  accepts_nested_attributes_for :results
  validates :examination_id, uniqueness: {scope: :user_id, message: "は既に受験済です"}

  def score
    results.select {|r| r.correct?}.length * 10 #点数を出す
  end

  def pass?
    score >= 10
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trials
  has_many :results, through: :trials

  def passed?(examination_id)
    # trials.select {|t| t.examination_id == examination_id}.present?
    trials.where(examination_id: examination_id).count > 0
  end
end

app/controllers/admin/examinations_controller.rb
module Admin
  class ExaminationsController < ApplicationController
    def index
      @examinations = Examination.all #Examinationテーブル(月一テスト一覧)のすべてのデータが取り出せる
    end

    def show
      @examination = Examination.find(params[:id])    #Examinationテーブルのidに紐付いた一つのカラムをとってくる(一ヶ月分の問題)
      @questions = @examination.questions #1レコードに紐付いているquestionsのデータ(問題一覧)　
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  def index
    @examinations = Examination.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text)
    end
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  def new
    @examination = Examination.find(params[:examination_id])
    @trial = Trial.new examination_id: params[:examination_id], user_id: current_user.id
    @examination.questions.each do |question|
      @trial.results << Result.new(question_id: question.id)
    end
  end

  def create
    @examination = Examination.find(params[:examination_id])
    @trial = Trial.new(trial_params)
    @trial.user_id = current_user.id
    @trial.examination_id = @examination.id
    if @trial.valid?
      if @trial.pass?
        @trial.save
        redirect_to examinations_path, notice: "#{@trial.score}点、合格です！"
      else
        flash.now[:alert] = "不合格です"
        render :new
      end
    else
      flash.now[:alert] = "選択されてない問題があります"
      render :new
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def trial_params
      params.require(:trial).permit(results_attributes: [ :answer, :question_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/admin/examinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>問題一覧</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examinations.each do |examination| %>
      <tr>
        <td><%= examination.description %></td>
        <td><%= link_to 'Show', admin_examination_path(examination) %></td>
        <td><%= link_to 'Edit', edit_examination_path(examination) %></td>
        <td><%= link_to 'Destroy', examination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New examination', new_examination_path %>

app/views/admin/examinations/show.html.erb
<h3><%= @examination.description %></h3> <!-- 値 -->
<table border="1">
  <tbody>
  <% @questions.each do |question| %> <!-- 実行はするけど表示されない -->
    <tr>
      <td><%= question.text %></td>
      <td><%= question.answer_text %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/examinations/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>問題一覧</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examinations.each do |examination| %>
      <tr>
        <td><%= examination.description %></td>
        <td>
          <% if current_user.passed?(examination.id) %>
            受験済
          <% else %>
            <%= link_to '受験する', new_examination_trial_path(examination) %>
          <% end %>
        </td>
        <td><%= link_to 'Show', examination %></td>
        <td><%= link_to 'Edit', edit_examination_path(examination) %></td>
        <td><%= link_to 'Destroy', examination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New examination', new_examination_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecurityDojo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>問題一覧</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/trials/create.html.erb
<h1>Trials#create</h1>
<p>Find me in app/views/trials/create.html.erb</p>

app/views/trials/new.html.erb
<h1>Trials#new</h1>
<%= form_for [@examination, @trial] do |f| %>
  <% if @trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trial.errors.count, "error") %> prohibited this trial from being saved:</h2>

      <ul>
      <% @trial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :results do |result_form| %>
    <%= result_form.label :answer, result_form.object.text %>
    <%#= result_form.text_field :answer %>
    <%= result_form.radio_button :answer, 1 %> <%= result_form.label :answer_1, '×' %>
    <%= result_form.radio_button :answer, 2 %> <%=result_form.label :answer_2, '○' %>
    <%= result_form.hidden_field :question_id, value: result_form.object.question_id %>
    <br>
  <% end %>
  <%= f.submit %>
<% end %>